# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
t: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tabe_dive_development
test:
  <<: *default
  database: tabe_dive_test
production:
  <<: *default
  database: tabe_dive_production
  username: tabe_dive
  password: <%= ENV['TABE_DIVE_DATABASE_PASSWORD'] %>

